version: '3.7' 
services:
  nats-main:
    image: nats:1.4.0 
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
  streaming:
    image: nats-streaming:0.11.2
    ports:
      - 4223:4223
      - 8223:8223
    command: -store file -dir datastore -ns nats://nats-main:4222
    links:
      - nats-main
